# Settings regarding PlaceholderAPI.
#
# Type: Table of properties
[placeholderapi]
# Whether placeholders should be synchronised with plugin messages.
# This also needs to be set on the Bukkit plugin.
# This disables all features on the Bukkit plugin.
#
# Type: Boolean
# Default: true
plugin-messaging = true

# Settings regarding header & footer for players.
#
# Type: Table of properties
[header-footer]
# Whether header & footer should be displayed.
#
# Type: Boolean
# Default: true
enabled = true

# How often it should refresh in milliseconds.
#
# Type: Integer
refresh-interval = 50

# The header to display.
# This can be empty ([]) for no header.
#
# Type: List of strings
header = [
  "&6&lServer Name",
  "",
  "&4You're cool :sunglasses:",
]

# The footer to display.
# This can be empty ([]) for no footer.
#
# Type: List of strings
footer = [
  "&9Wee!!",
]

# Global settings for groups.
#
# Type: Table of properties
[group-settings]
# How often it should refresh in milliseconds.
#
# Type: Integer
refresh-interval = 50

# Settings of groups to use for tab.
#
# Removing a value altogether results in it being handed off to the next lower
# weight group that has the property. If you set a value to be blank, it will
# not do so, but will also have no functionality, meaning you can wipe parts by
# setting them blank, and inherit others by not specifying them at all.
#
# Type: Array of groups
[[groups]]
# The name of the group.
# This is used in the permission node, `tab.groups.<name>`
#
# Type: String
# This is required for the plugin to be functioning.
name = "test"

# The weight of the group.
# Prefer unique values, as that will not cause any unpredicted behaviour.
#
# A higher value means its properties weigh in more, so a weight 10 wins over a
# weight 5 on e.g. prefix. This then means it'll use the prefix of the weight 10
# instead of the weight 5.
#
# Type: Integer
weight = 30

# The prefix to use for the player in the tab list.
# This is limited to 64 characters if `player-name` is not set.
#
# Type: String
prefix = "&aTest "

# The suffix to use for the player in the tab list.
# This is limited to 64 characters if `player-name` is not set.
#
# Type: String
suffix = "&c Lol"

# The name to use for the player in the tab list.
# This is not limited by characters.
#
# Type: String
player-name = "&c%player_name%"

# The ordering of the group.
# A higher ordering means lower in the player list.
#
# Type: Integer
# Max value: 99999 - values over this are *permitted* but will NOT *work*
order = 0